version: '3.7' 

services:
  api:
    build: ./
    depends_on:
      - mongodb
      - redis
    ports:
      - "6000:8000"
    environment:
      - MONGOURI=mongodb://mongodb:27017/
      - REDISURI=redis://redis:6379
      - PORT = ":8000"
      - QRDURATION = 25
      - JWT_SECRET_KEY = "Baboon"
      - JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT = 360

  mongodb:
    image: mongo:latest
    container_name: monogodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  mongodata:
  redisdata: